version: '2'

services:
# ------------------------------------------
# wordpress wp-blog
# ------------------------------------------
    wp-blog:
      image: wordpress
      env_file: .env
      ports:
        - 80
      volumes:
          - /home/docker-user/wp-blog/wp-content/uploads:/var/www/html/wp-content/uploads
          - /home/docker-user/wp-blog/wp-content/plugins:/var/www/html/wp-content/plugins
          - /home/docker-user/wp-blog/wp-content/themes:/var/www/html/wp-content/themes
      tty: true
      restart: always
      environment:
        VIRTUAL_HOST: $VIRTUAL_HOST
        LETSENCRYPT_HOST: $LETSENCRYPT_HOST
        LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
        WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
        WORDPRESS_DB_USER: $WORDPRESS_DB_USER
        WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
        WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      container_name: wp-blog

networks:
  default:
    external:
      name: shared